-- Seed: diagnostic_fields (catálogo de field_id estáveis do formulário — decisão D8)
insert into public.diagnostic_fields (field_id, etapa, ordem, label, tipo) values
  ('respondent_nome', 'identidade', 1, 'Seu nome', 'text'),
  ('respondent_email', 'identidade', 2, 'Seu melhor e-mail', 'email'),
  ('goal_faturamento', 'identidade', 3, 'Quanto você quer faturar por mês?', 'number'),
  ('goal_retirada', 'identidade', 4, 'Quanto deseja retirar para você por mês?', 'number'),
  ('max_atendimentos', 'identidade', 5, 'Quantos atendimentos individuais por semana você quer sustentar no máximo?', 'number'),
  ('modelo_desejado', 'identidade', 6, 'Qual modelo você deseja hoje?', 'select'),
  ('receita_atual', 'economia_atual', 1, 'Faturamento mensal atual', 'number'),
  ('pacientes_atuais', 'economia_atual', 2, 'Pacientes / atendimentos semanais atuais', 'number'),
  ('valor_medio_sessao', 'economia_atual', 3, 'Valor médio por sessão', 'number'),
  ('custos_mensais', 'economia_atual', 4, 'Custos mensais da clínica', 'number'),
  ('concentracao_top3', 'economia_atual', 5, 'Percentual da receita vindo dos 3 maiores pacientes', 'number'),
  ('concentracao_canal', 'economia_atual', 6, 'Percentual de novos pacientes vindo do principal canal', 'number'),
  ('estrutura_contrato', 'estrutura', 1, 'Contrato / acordo terapêutico estruturado', 'checkbox'),
  ('estrutura_prontuario', 'estrutura', 2, 'Prontuário com rotina sustentável', 'checkbox'),
  ('estrutura_cadastro', 'estrutura', 3, 'Cadastro inicial padronizado', 'checkbox'),
  ('estrutura_cancelamento', 'estrutura', 4, 'Política de cancelamento e reagendamento clara', 'checkbox'),
  ('estrutura_reajuste', 'estrutura', 5, 'Regra de reajuste definida', 'checkbox'),
  ('estrutura_agenda_inclui', 'estrutura', 6, 'Agenda inclui prontuário, supervisão e estudo', 'checkbox'),
  ('estrutura_protocolos', 'estrutura', 7, 'Protocolos para situações recorrentes', 'checkbox'),
  ('financas_contas_separadas', 'financas', 1, 'Contas pessoais e da clínica estão separadas', 'checkbox'),
  ('financas_custo_conhecido', 'financas', 2, 'Você sabe o custo mensal real da clínica', 'checkbox'),
  ('financas_retirada_previsivel', 'financas', 3, 'Existe retirada / pró-labore minimamente previsível', 'checkbox'),
  ('financas_reserva', 'financas', 4, 'Existe reserva financeira da clínica', 'checkbox'),
  ('financas_acompanha_indicadores', 'financas', 5, 'Você acompanha faturamento, ticket e ocupação mensalmente', 'checkbox'),
  ('financas_ponto_equilibrio', 'financas', 6, 'Você conhece seu ponto de equilíbrio', 'checkbox'),
  ('pos_publico_claro', 'posicionamento', 1, 'Tenho clareza de quem atendo melhor e em quais contextos meu trabalho faz mais sentido', 'rating'),
  ('pos_diferenciais', 'posicionamento', 2, 'Consigo nomear meus diferenciais sem depender apenas de formação ou abordagem', 'rating'),
  ('pos_presenca_coerente', 'posicionamento', 3, 'Minha presença profissional comunica de forma coerente quem sou e para quem trabalho', 'rating'),
  ('pos_entendem_por_que_agora', 'posicionamento', 4, 'Quem chega entende por que poderia me procurar agora, sem eu precisar explicar tudo no privado', 'rating'),
  ('pos_comunica_valor', 'posicionamento', 5, 'Minha comunicação ajuda a pessoa a perceber adequação e valor, em vez de comparar apenas preço', 'rating'),
  ('acq_sabe_origem', 'captacao', 1, 'Sei de onde vieram meus últimos 10 pacientes / contatos', 'checkbox'),
  ('acq_dois_canais', 'captacao', 2, 'Tenho pelo menos 2 canais ativos de descoberta ou indicação', 'checkbox'),
  ('acq_presenca_clara', 'captacao', 3, 'Minha presença online permite entender rapidamente o que ofereço', 'checkbox'),
  ('acq_rotina_relacionamento', 'captacao', 4, 'Tenho uma rotina de relacionamento / parcerias / presença, não apenas postagens pontuais', 'checkbox'),
  ('acq_primeiro_contato_organizado', 'captacao', 5, 'Meu primeiro contato é organizado e reduz dúvidas sobre funcionamento, formato e próximos passos', 'checkbox'),
  ('acq_nao_depende_uma_fonte', 'captacao', 6, 'A entrada de novos pacientes não depende quase totalmente de uma única pessoa ou fonte', 'checkbox'),
  ('mod_servico_claro', 'modelo', 1, 'Meu serviço principal está claro em formato, público e condições de atendimento', 'rating'),
  ('mod_preco_criterios', 'modelo', 2, 'O preço praticado hoje é sustentado por critérios, e não apenas pelo que acho que o mercado aceita', 'rating'),
  ('mod_novo_servico_resolve', 'modelo', 3, 'Se eu criar outro serviço, sei qual problema de modelo ele resolverá', 'rating'),
  ('mod_agenda_comporta', 'modelo', 4, 'Minha agenda e energia atuais comportam expansão sem comprometer o serviço principal', 'rating'),
  ('energia_desgaste', 'fechamento', 1, 'Como está seu desgaste com a agenda atual?', 'select'),
  ('sensacao_atual', 'fechamento', 2, 'Hoje, qual sensação mais descreve sua clínica?', 'select')

on conflict (field_id) do update set etapa = excluded.etapa, ordem = excluded.ordem, label = excluded.label, tipo = excluded.tipo;